// <auto-generated />
using System;
using EF.BongaCC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF.BongaCC.Data.Migrations
{
    [DbContext(typeof(BongaCCDbContext))]
    [Migration("20190418092338_CostBreakDownUpdatedXXX")]
    partial class CostBreakDownUpdatedXXX
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF.BongaCC.Core.Model.Activity", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("Description");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ActivityCode", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityCodeDesc");

                    b.Property<DateTime>("AddedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("ActivityCode");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ActivityDetails", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<long?>("BudgetBookCommitmentsID");

                    b.Property<string>("Description");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<decimal>("Quantity");

                    b.Property<decimal>("Rate");

                    b.HasKey("ID");

                    b.HasIndex("BudgetBookCommitmentsID");

                    b.ToTable("ActivityDetails");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ActivityType", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityName");

                    b.Property<DateTime>("AddedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("ActivityType");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ApprovalDecision", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("ColorCode");

                    b.Property<string>("Decision");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("Discipline");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.AppUsers", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<int>("Deligate");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsGuestAcct");

                    b.Property<DateTime>("LoginTime");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Password");

                    b.Property<string>("RefInd");

                    b.Property<int>("RoleId");

                    b.Property<int>("Status");

                    b.Property<string>("UserMail");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Area", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("AreaName");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Asset", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("AssetName");

                    b.Property<string>("Location");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBasis", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("BudgetBase");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("BudgetBasis");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBook", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ActivityCodeID");

                    b.Property<long>("ActivityID");

                    b.Property<long?>("ActivityOwnerID");

                    b.Property<long>("ActivityTypeID");

                    b.Property<DateTime>("AddedDate");

                    b.Property<long>("BudgetBasisID");

                    b.Property<long>("CapexOpexID");

                    b.Property<long>("ContractID");

                    b.Property<int>("DirectAllocated");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<decimal>("NAPIMSBUDGETDollar");

                    b.Property<decimal>("NAPIMSBUDGETFDollar");

                    b.Property<decimal>("NAPIMSBUDGETNaira");

                    b.Property<decimal>("OPYearBudgetDollar");

                    b.Property<decimal>("OPYearBudgetFDollar");

                    b.Property<decimal>("OPYearBudgetNaira");

                    b.Property<decimal>("Q1FYLEDollar");

                    b.Property<decimal>("Q1FYLEFDollar");

                    b.Property<decimal>("Q1FYLENaira");

                    b.Property<decimal>("Q2FYLEDollar");

                    b.Property<decimal>("Q2FYLEFDollar");

                    b.Property<decimal>("Q2FYLENaira");

                    b.Property<decimal>("Q3FYLEDollar");

                    b.Property<decimal>("Q3FYLEFDollar");

                    b.Property<decimal>("Q3FYLENaira");

                    b.Property<decimal>("Q4FYLEDollar");

                    b.Property<decimal>("Q4FYLEFDollar");

                    b.Property<decimal>("Q4FYLENaira");

                    b.Property<long>("ScopeID");

                    b.Property<long?>("SponsorID");

                    b.Property<long>("UapCodeID");

                    b.Property<long>("UapRollUpCodeID");

                    b.Property<int>("YYear");

                    b.Property<long>("wbsID");

                    b.HasKey("ID");

                    b.HasIndex("ActivityCodeID");

                    b.HasIndex("ActivityID");

                    b.HasIndex("ActivityTypeID");

                    b.HasIndex("BudgetBasisID");

                    b.HasIndex("CapexOpexID");

                    b.HasIndex("ContractID");

                    b.HasIndex("ScopeID");

                    b.HasIndex("SponsorID");

                    b.HasIndex("UapCodeID");

                    b.HasIndex("UapRollUpCodeID");

                    b.HasIndex("wbsID");

                    b.ToTable("BudgetBook");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBookCommitments", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("ApprovalComment");

                    b.Property<long?>("ApprovalID");

                    b.Property<long>("ApproverID");

                    b.Property<long?>("BudgetBookID");

                    b.Property<DateTime>("CCPSessionDate");

                    b.Property<string>("Comitmntno");

                    b.Property<decimal>("Commitment");

                    b.Property<long?>("FocalPointID");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<decimal>("Savings");

                    b.HasKey("ID");

                    b.HasIndex("ApprovalID");

                    b.HasIndex("BudgetBookID");

                    b.HasIndex("FocalPointID");

                    b.ToTable("BudgetBookCommitments");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Commitments", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<long?>("ApprovalDecisionID");

                    b.Property<int>("CapexOpex");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("PONumber");

                    b.Property<decimal>("POValue");

                    b.Property<string>("PRNumber");

                    b.Property<decimal>("PRValue");

                    b.Property<string>("TeamIndicator");

                    b.Property<string>("approvalComment");

                    b.Property<long?>("approvalID");

                    b.Property<long>("approverID");

                    b.Property<long>("assetID");

                    b.Property<long>("checkedbyID");

                    b.Property<string>("comitmntno");

                    b.Property<decimal>("commitment");

                    b.Property<string>("contractnovendor");

                    b.Property<long>("departmentID");

                    b.Property<long>("facilityID");

                    b.Property<long?>("focalpointID");

                    b.Property<long>("groupID");

                    b.Property<string>("justification");

                    b.Property<decimal>("napimsDollar");

                    b.Property<decimal>("napimsFunctionalDollar");

                    b.Property<decimal>("napimsNaira");

                    b.Property<DateTime>("periodfrom");

                    b.Property<DateTime>("periodto");

                    b.Property<DateTime>("previous");

                    b.Property<decimal>("requestDollar");

                    b.Property<decimal>("requestFunctionalDollar");

                    b.Property<decimal>("requestNaira");

                    b.Property<decimal>("savings");

                    b.Property<long>("sponsorID");

                    b.Property<long>("statusID");

                    b.Property<long>("teamID");

                    b.Property<string>("threat");

                    b.Property<string>("title");

                    b.Property<long>("typeID");

                    b.Property<long>("vehicleID");

                    b.Property<long>("wbsID");

                    b.HasKey("ID");

                    b.HasIndex("ApprovalDecisionID");

                    b.HasIndex("assetID");

                    b.HasIndex("departmentID");

                    b.HasIndex("facilityID");

                    b.HasIndex("focalpointID");

                    b.HasIndex("groupID");

                    b.HasIndex("statusID");

                    b.HasIndex("teamID");

                    b.HasIndex("typeID");

                    b.HasIndex("vehicleID");

                    b.HasIndex("wbsID");

                    b.ToTable("Commitments");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Contract", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("ContractName");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ContractProcurementVehicle", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("VehicleName");

                    b.HasKey("ID");

                    b.ToTable("ContractProcurementVehicle");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.CXOX", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("CapexOpex");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("CapexOpex");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Department", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("DepartmentName");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ExchangeRate", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<decimal>("ExchangeRateValue");

                    b.Property<int>("MMonth");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("YYear");

                    b.HasKey("ID");

                    b.ToTable("ExchangeRate");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Facility", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<int>("Agg");

                    b.Property<long>("AreaID");

                    b.Property<string>("Code");

                    b.Property<string>("FacilityName");

                    b.Property<int>("Location");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.HasIndex("AreaID");

                    b.ToTable("Facility");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.FileUpload", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<long?>("BudgetBookCommitmentsID");

                    b.Property<long?>("CommitmentID");

                    b.Property<string>("FileNames");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<byte[]>("UploadFiles")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("BudgetBookCommitmentsID");

                    b.HasIndex("CommitmentID");

                    b.ToTable("FileUpload");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.PlannedEmmergency", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("PlanEmmerType");

                    b.HasKey("ID");

                    b.ToTable("PlannedEmmergency");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.PurchasingGroup", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("GroupName");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("PurchasingGroup");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.RequestStatus", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("ReqstStatus");

                    b.HasKey("ID");

                    b.ToTable("RequestStatus");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Scope", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Purpose");

                    b.HasKey("ID");

                    b.ToTable("Scope");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Team", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("TeamName");

                    b.HasKey("ID");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.UapCode", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("UapCodeDesc");

                    b.HasKey("ID");

                    b.ToTable("UapCode");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.UapRollUpCode", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("UapRollUpCodeDesc");

                    b.HasKey("ID");

                    b.ToTable("UapRollUpCode");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.WBS", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("CostObjects");

                    b.Property<string>("CostObjectsDescription");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ID");

                    b.ToTable("WBS");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ActivityDetails", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.BudgetBookCommitments", "BudgetBookCommitments")
                        .WithMany("ActivityDetails")
                        .HasForeignKey("BudgetBookCommitmentsID");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBook", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.ActivityCode", "ActivityCode")
                        .WithMany("BudgetBook")
                        .HasForeignKey("ActivityCodeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.Activity", "Activity")
                        .WithMany("BudgetBook")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.ActivityType", "ActivityType")
                        .WithMany("BudgetBook")
                        .HasForeignKey("ActivityTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.BudgetBasis", "BudgetBasis")
                        .WithMany("BudgetBook")
                        .HasForeignKey("BudgetBasisID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.CXOX", "CapexOpex")
                        .WithMany("BudgetBook")
                        .HasForeignKey("CapexOpexID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.Contract", "Contract")
                        .WithMany("BudgetBook")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.Scope", "Scope")
                        .WithMany("BudgetBook")
                        .HasForeignKey("ScopeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.AppUsers", "Sponsor")
                        .WithMany("BudgetBook")
                        .HasForeignKey("SponsorID");

                    b.HasOne("EF.BongaCC.Core.Model.UapCode", "UapCode")
                        .WithMany("BudgetBook")
                        .HasForeignKey("UapCodeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.UapRollUpCode", "UapRollUpCode")
                        .WithMany("BudgetBook")
                        .HasForeignKey("UapRollUpCodeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.WBS", "WBS")
                        .WithMany("BudgetBook")
                        .HasForeignKey("wbsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBookCommitments", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.ApprovalDecision", "ApprovalDecision")
                        .WithMany("BudgetBookCommitments")
                        .HasForeignKey("ApprovalID");

                    b.HasOne("EF.BongaCC.Core.Model.BudgetBook", "BudgetBook")
                        .WithMany("BudgetBookCommitments")
                        .HasForeignKey("BudgetBookID");

                    b.HasOne("EF.BongaCC.Core.Model.AppUsers", "FocalPoint")
                        .WithMany("BudgetBookCommitments")
                        .HasForeignKey("FocalPointID");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Commitments", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.ApprovalDecision", "ApprovalDecision")
                        .WithMany("Commitments")
                        .HasForeignKey("ApprovalDecisionID");

                    b.HasOne("EF.BongaCC.Core.Model.Asset", "Asset")
                        .WithMany("Commitments")
                        .HasForeignKey("assetID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.Department", "Department")
                        .WithMany("Commitments")
                        .HasForeignKey("departmentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.Facility", "Facility")
                        .WithMany("Commitments")
                        .HasForeignKey("facilityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.AppUsers", "FocalPoint")
                        .WithMany("Commitments")
                        .HasForeignKey("focalpointID");

                    b.HasOne("EF.BongaCC.Core.Model.PurchasingGroup", "PurchasingGroup")
                        .WithMany("Commitments")
                        .HasForeignKey("groupID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.RequestStatus", "RequestStatus")
                        .WithMany("Commitments")
                        .HasForeignKey("statusID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.Team", "Teams")
                        .WithMany("Commitments")
                        .HasForeignKey("teamID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.PlannedEmmergency", "PlannedEmmergency")
                        .WithMany("Commitments")
                        .HasForeignKey("typeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.ContractProcurementVehicle", "ContractProcurementVehicle")
                        .WithMany("Commitments")
                        .HasForeignKey("vehicleID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EF.BongaCC.Core.Model.WBS", "WBS")
                        .WithMany()
                        .HasForeignKey("wbsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Facility", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.Area", "Area")
                        .WithMany("Facilities")
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.FileUpload", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.BudgetBookCommitments", "BudgetBookCommitments")
                        .WithMany("FileUploads")
                        .HasForeignKey("BudgetBookCommitmentsID");

                    b.HasOne("EF.BongaCC.Core.Model.Commitments", "Commitments")
                        .WithMany("FileUploads")
                        .HasForeignKey("CommitmentID");
                });
#pragma warning restore 612, 618
        }
    }
}
