// <auto-generated />
using System;
using EF.BongaCC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF.BongaCC.Data.Migrations
{
    [DbContext(typeof(BongaCCDbContext))]
    [Migration("20210930211526_Workstream")]
    partial class Workstream
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF.BongaCC.Core.Model.Activity", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ActivityCode", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AccountableManagerID")
                        .HasColumnType("bigint");

                    b.Property<string>("ActivityCodeDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ActivityCodeWorkStreamID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ActivityOwnerID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LineManagerID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ActivityCodeWorkStreamID");

                    b.HasIndex("LineManagerID");

                    b.ToTable("ActivityCode");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ActivityCodeWorkStream", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkFlowType")
                        .HasColumnType("int");

                    b.Property<string>("WorkStream")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkStreamDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ActivityCodeWorkStream");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ActivityDetails", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("BudgetBookCommitmentsID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BudgetBookID")
                        .HasColumnType("bigint");

                    b.Property<long?>("CurrenciesID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FixedExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("iYear")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BudgetBookCommitmentsID");

                    b.HasIndex("BudgetBookID");

                    b.HasIndex("CurrenciesID");

                    b.ToTable("ActivityDetails");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ActivityType", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("ActivityType");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.AppUsers", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Deligate")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGuestAcct")
                        .HasColumnType("bit");

                    b.Property<long?>("LineManagerID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LineManagerID");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ApprovalDecision", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Decision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Discipline");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Area", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Asset", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBasis", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BudgetBase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("BudgetBasis");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBook", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ActivityCodeID")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityID")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityTypeID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AppUsersID")
                        .HasColumnType("bigint");

                    b.Property<long>("BudgetBasisID")
                        .HasColumnType("bigint");

                    b.Property<long>("CapexOpexID")
                        .HasColumnType("bigint");

                    b.Property<long>("ContractID")
                        .HasColumnType("bigint");

                    b.Property<int>("DirectAllocated")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NAPIMSBUDGETDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NAPIMSBUDGETFDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NAPIMSBUDGETNaira")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ScopeID")
                        .HasColumnType("bigint");

                    b.Property<long>("UapCodeID")
                        .HasColumnType("bigint");

                    b.Property<long>("UapRollUpCodeID")
                        .HasColumnType("bigint");

                    b.Property<int>("YYear")
                        .HasColumnType("int");

                    b.Property<long>("wbsID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ActivityCodeID");

                    b.HasIndex("ActivityID");

                    b.HasIndex("ActivityTypeID");

                    b.HasIndex("AppUsersID");

                    b.HasIndex("BudgetBasisID");

                    b.HasIndex("CapexOpexID");

                    b.HasIndex("ContractID");

                    b.HasIndex("ScopeID");

                    b.HasIndex("UapCodeID");

                    b.HasIndex("UapRollUpCodeID");

                    b.HasIndex("wbsID");

                    b.ToTable("BudgetBook");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBookCommitments", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ActivityOwnerID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ApprovalID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ApproverID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BudgetBookID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CCPSessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comitmntno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Commitment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("FocalPointID")
                        .HasColumnType("bigint");

                    b.Property<long?>("LineManagerID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("POValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PRNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PRValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Savings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SponsorID")
                        .HasColumnType("bigint");

                    b.Property<string>("contractnovendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("groupID")
                        .HasColumnType("bigint");

                    b.Property<int>("iYear")
                        .HasColumnType("int");

                    b.Property<string>("justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sPeriodfrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("statusID")
                        .HasColumnType("bigint");

                    b.Property<long?>("teamID")
                        .HasColumnType("bigint");

                    b.Property<string>("threat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("typeID")
                        .HasColumnType("bigint");

                    b.Property<long?>("vehicleID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ApprovalID");

                    b.HasIndex("BudgetBookID");

                    b.HasIndex("FocalPointID");

                    b.HasIndex("groupID");

                    b.HasIndex("statusID");

                    b.HasIndex("teamID");

                    b.HasIndex("typeID");

                    b.HasIndex("vehicleID");

                    b.ToTable("BudgetBookCommitments");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBookFinanceYear", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("BudgetBookID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NAPIMSBUDGETDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NAPIMSBUDGETFDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NAPIMSBUDGETNaira")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OPYearBudgetDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OPYearBudgetFDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OPYearBudgetNaira")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q1FYLEDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q1FYLEFDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q1FYLENaira")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q2FYLEDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q2FYLEFDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q2FYLENaira")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q3FYLEDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q3FYLEFDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q3FYLENaira")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q4FYLEDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q4FYLEFDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q4FYLENaira")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YYear")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BudgetBookID");

                    b.ToTable("BudgetBookFinanceYear");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetUploader", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountableManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Budgetbasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectAllocated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OPYearBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScopePurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UapCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UapRollUpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YYear")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BudgetUploaders");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetUploaderTransformed", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountableManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Budgetbasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectAllocated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OPYearBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScopePurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UapCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UapRollUpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YYear")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BudgetUploaderTransformeds");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.CXOX", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CapexOpex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("CapexOpex");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Commitments", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ApprovalDecisionID")
                        .HasColumnType("bigint");

                    b.Property<int>("CapexOpex")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("POValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PRNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PRValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeamIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approvalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("approvalID")
                        .HasColumnType("bigint");

                    b.Property<long>("approverID")
                        .HasColumnType("bigint");

                    b.Property<long>("assetID")
                        .HasColumnType("bigint");

                    b.Property<long>("checkedbyID")
                        .HasColumnType("bigint");

                    b.Property<string>("comitmntno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("commitment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("contractnovendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("departmentID")
                        .HasColumnType("bigint");

                    b.Property<long>("facilityID")
                        .HasColumnType("bigint");

                    b.Property<long?>("focalpointID")
                        .HasColumnType("bigint");

                    b.Property<long>("groupID")
                        .HasColumnType("bigint");

                    b.Property<string>("justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("napimsDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("napimsFunctionalDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("napimsNaira")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("periodfrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("periodto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("previous")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("requestDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("requestFunctionalDollar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("requestNaira")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("sPeriodfrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("savings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("sponsorID")
                        .HasColumnType("bigint");

                    b.Property<long>("statusID")
                        .HasColumnType("bigint");

                    b.Property<long>("teamID")
                        .HasColumnType("bigint");

                    b.Property<string>("threat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("typeID")
                        .HasColumnType("bigint");

                    b.Property<long>("vehicleID")
                        .HasColumnType("bigint");

                    b.Property<long>("wbsID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ApprovalDecisionID");

                    b.HasIndex("assetID");

                    b.HasIndex("departmentID");

                    b.HasIndex("facilityID");

                    b.HasIndex("focalpointID");

                    b.HasIndex("groupID");

                    b.HasIndex("statusID");

                    b.HasIndex("teamID");

                    b.HasIndex("typeID");

                    b.HasIndex("vehicleID");

                    b.HasIndex("wbsID");

                    b.ToTable("Commitments");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Contract", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ContractProcurementVehicle", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContractProcurementVehicle");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Currencies", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Codes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Department", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ExchangeRate", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FloatingExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MMonth")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("YYear")
                        .HasColumnType("int");

                    b.Property<int>("iDay")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ExchangeRate");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Facility", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Agg")
                        .HasColumnType("int");

                    b.Property<long>("AreaID")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AreaID");

                    b.ToTable("Facility");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.FileUpload", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("BudgetBookCommitmentsID")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommitmentID")
                        .HasColumnType("bigint");

                    b.Property<string>("FileNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<byte[]>("UploadFiles")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ID");

                    b.HasIndex("BudgetBookCommitmentsID");

                    b.HasIndex("CommitmentID");

                    b.ToTable("FileUpload");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.PlannedEmmergency", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanEmmerType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PlannedEmmergency");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.PurchasingGroup", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("PurchasingGroup");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.RequestStatus", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReqstStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RequestStatus");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Scope", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Scope");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Team", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.UapCode", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UapCodeDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UapCode");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.UapRollUpCode", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UapRollUpCodeDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UapRollUpCode");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.WBS", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CostObjects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostObjectsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("WBS");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ActivityCode", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.ActivityCodeWorkStream", "ActivityCodeWorkStream")
                        .WithMany("ActivityCodes")
                        .HasForeignKey("ActivityCodeWorkStreamID");

                    b.HasOne("EF.BongaCC.Core.Model.AppUsers", "LineManager")
                        .WithMany("ActivityCodes")
                        .HasForeignKey("LineManagerID");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.ActivityDetails", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.BudgetBookCommitments", "BudgetBookCommitments")
                        .WithMany("ActivityDetails")
                        .HasForeignKey("BudgetBookCommitmentsID");

                    b.HasOne("EF.BongaCC.Core.Model.BudgetBook", "BudgetBook")
                        .WithMany("ActivityDetails")
                        .HasForeignKey("BudgetBookID");

                    b.HasOne("EF.BongaCC.Core.Model.Currencies", "Currencies")
                        .WithMany("ActivityDetails")
                        .HasForeignKey("CurrenciesID");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.AppUsers", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.AppUsers", "LineManager")
                        .WithMany("ActivityOwners")
                        .HasForeignKey("LineManagerID");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBook", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.ActivityCode", "ActivityCode")
                        .WithMany("BudgetBook")
                        .HasForeignKey("ActivityCodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.Activity", "Activity")
                        .WithMany("BudgetBook")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.ActivityType", "ActivityType")
                        .WithMany("BudgetBook")
                        .HasForeignKey("ActivityTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.AppUsers", null)
                        .WithMany("BudgetBook")
                        .HasForeignKey("AppUsersID");

                    b.HasOne("EF.BongaCC.Core.Model.BudgetBasis", "BudgetBasis")
                        .WithMany("BudgetBook")
                        .HasForeignKey("BudgetBasisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.CXOX", "CapexOpex")
                        .WithMany("BudgetBook")
                        .HasForeignKey("CapexOpexID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.Contract", "Contract")
                        .WithMany("BudgetBook")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.Scope", "Scope")
                        .WithMany("BudgetBook")
                        .HasForeignKey("ScopeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.UapCode", "UapCode")
                        .WithMany("BudgetBook")
                        .HasForeignKey("UapCodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.UapRollUpCode", "UapRollUpCode")
                        .WithMany("BudgetBook")
                        .HasForeignKey("UapRollUpCodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.WBS", "WBS")
                        .WithMany("BudgetBook")
                        .HasForeignKey("wbsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBookCommitments", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.ApprovalDecision", "ApprovalDecision")
                        .WithMany("BudgetBookCommitments")
                        .HasForeignKey("ApprovalID");

                    b.HasOne("EF.BongaCC.Core.Model.BudgetBook", "BudgetBook")
                        .WithMany("BudgetBookCommitments")
                        .HasForeignKey("BudgetBookID");

                    b.HasOne("EF.BongaCC.Core.Model.AppUsers", "FocalPoint")
                        .WithMany("BudgetBookCommitments")
                        .HasForeignKey("FocalPointID");

                    b.HasOne("EF.BongaCC.Core.Model.PurchasingGroup", "PurchasingGroup")
                        .WithMany("BudgetBookCommitments")
                        .HasForeignKey("groupID");

                    b.HasOne("EF.BongaCC.Core.Model.RequestStatus", "RequestStatus")
                        .WithMany("BudgetBookCommitments")
                        .HasForeignKey("statusID");

                    b.HasOne("EF.BongaCC.Core.Model.Team", "Teams")
                        .WithMany("BudgetBookCommitments")
                        .HasForeignKey("teamID");

                    b.HasOne("EF.BongaCC.Core.Model.PlannedEmmergency", "PlannedEmmergency")
                        .WithMany("BudgetBookCommitments")
                        .HasForeignKey("typeID");

                    b.HasOne("EF.BongaCC.Core.Model.ContractProcurementVehicle", "ContractProcurementVehicle")
                        .WithMany("BudgetBookCommitments")
                        .HasForeignKey("vehicleID");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.BudgetBookFinanceYear", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.BudgetBook", "BudgetBook")
                        .WithMany()
                        .HasForeignKey("BudgetBookID");
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Commitments", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.ApprovalDecision", "ApprovalDecision")
                        .WithMany("Commitments")
                        .HasForeignKey("ApprovalDecisionID");

                    b.HasOne("EF.BongaCC.Core.Model.Asset", "Asset")
                        .WithMany("Commitments")
                        .HasForeignKey("assetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.Department", "Department")
                        .WithMany("Commitments")
                        .HasForeignKey("departmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.Facility", "Facility")
                        .WithMany("Commitments")
                        .HasForeignKey("facilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.AppUsers", "FocalPoint")
                        .WithMany("Commitments")
                        .HasForeignKey("focalpointID");

                    b.HasOne("EF.BongaCC.Core.Model.PurchasingGroup", "PurchasingGroup")
                        .WithMany("Commitments")
                        .HasForeignKey("groupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.RequestStatus", "RequestStatus")
                        .WithMany("Commitments")
                        .HasForeignKey("statusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.Team", "Teams")
                        .WithMany("Commitments")
                        .HasForeignKey("teamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.PlannedEmmergency", "PlannedEmmergency")
                        .WithMany("Commitments")
                        .HasForeignKey("typeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.ContractProcurementVehicle", "ContractProcurementVehicle")
                        .WithMany("Commitments")
                        .HasForeignKey("vehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.BongaCC.Core.Model.WBS", "WBS")
                        .WithMany()
                        .HasForeignKey("wbsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.Facility", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.Area", "Area")
                        .WithMany("Facilities")
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EF.BongaCC.Core.Model.FileUpload", b =>
                {
                    b.HasOne("EF.BongaCC.Core.Model.BudgetBookCommitments", "BudgetBookCommitments")
                        .WithMany("FileUploads")
                        .HasForeignKey("BudgetBookCommitmentsID");

                    b.HasOne("EF.BongaCC.Core.Model.Commitments", "Commitments")
                        .WithMany("FileUploads")
                        .HasForeignKey("CommitmentID");
                });
#pragma warning restore 612, 618
        }
    }
}
